( function( blocks, element, blockEditor, components, i18n ) {
	'use strict';
	const el = element.createElement;
	const { __ } = i18n;
	const { InspectorControls, MediaUpload, MediaUploadCheck, useBlockProps } = blockEditor;
	const { Button, ButtonGroup, ColorPalette, PanelBody, RangeControl, SelectControl, TextareaControl, TextControl, ToggleControl } = components;
	const attributes = { imageId: { type: 'number', default: 0 }, imageUrl: { type: 'string', default: '' }, imageAlt: { type: 'string', default: '' }, mobileImageId: { type: 'number', default: 0 }, mobileImageUrl: { type: 'string', default: '' }, mobileImageAlt: { type: 'string', default: '' }, layers: { type: 'array', default: [] } };
	function clamp( value, min, max, fallback ) { const number = typeof value === 'number' ? value : fallback; return Math.max( min, Math.min( max, number ) ); }
	function layerId() { return 'layer-' + Date.now().toString( 36 ) + '-' + Math.random().toString( 36 ).slice( 2, 7 ); }
	function responsiveNumber( layer, key, mobile, fallback ) { const mobileKey = 'mobile' + key.charAt( 0 ).toUpperCase() + key.slice( 1 ); return mobile && typeof layer[ mobileKey ] === 'number' ? layer[ mobileKey ] : ( typeof layer[ key ] === 'number' ? layer[ key ] : fallback ); }
	function layerLabel( layer, index ) { if ( layer.type === 'image' ) return __( '画像レイヤー', 'cni-blocks' ) + ' ' + ( index + 1 ); const text = ( layer.content || '' ).replace( /\s+/g, ' ' ).trim(); return text ? text.slice( 0, 32 ) : __( 'テキスト', 'cni-blocks' ) + ' ' + ( index + 1 ); }
	function textLayer() { return { id: layerId(), type: 'text', content: __( 'テキストを入力', 'cni-blocks' ), customClass: '', role: 'heading', fontFamily: 'gothic', color: '#1f2937', fontWeight: '700', textAlign: 'center', lineHeight: 1.4, x: 50, y: 50, width: 30, fontSize: 22 }; }
	function imageLayer( media ) { return { id: layerId(), type: 'image', imageId: media.id || 0, imageUrl: media.url || '', imageAlt: media.alt || '', mobileImageId: 0, mobileImageUrl: '', mobileImageAlt: '', linkUrl: '', ariaLabel: '', newTab: false, customClass: '', x: 50, y: 50, width: 24 }; }
	blocks.registerBlockType( 'cni-blocks/image-text-layer', {
		apiVersion: 3, title: __( '画像テキストレイヤー', 'cni-blocks' ), icon: 'format-image', category: 'cni-blocks', description: __( '背景画像の上へ実テキストや画像を自由配置します。', 'cni-blocks' ), keywords: [ '画像', '図解', 'テキスト', 'インフォグラフィック' ], attributes: attributes, supports: { align: [ 'wide', 'full' ], anchor: true, html: false },
		edit: function( props ) {
			const a = props.attributes; const set = props.setAttributes; const layers = Array.isArray( a.layers ) ? a.layers : [];
			const deviceState = element.useState( 'desktop' ); const device = deviceState[ 0 ]; const setDevice = deviceState[ 1 ]; const mobile = device === 'mobile';
			const selectedState = element.useState( layers[ 0 ] ? layers[ 0 ].id : '' ); const selectedId = selectedState[ 0 ]; const setSelectedId = selectedState[ 1 ]; const dragRef = element.useRef( null );
			const selected = layers.find( function( layer ) { return layer.id === selectedId; } ) || null;
			const updateLayer = function( id, changes ) { set( { layers: layers.map( function( layer ) { return layer.id === id ? Object.assign( {}, layer, changes ) : layer; } ) } ); };
			const addText = function() { const layer = textLayer(); set( { layers: layers.concat( layer ) } ); setSelectedId( layer.id ); };
			const addImage = function( media ) { if ( ! media || ! media.url ) return; const layer = imageLayer( media ); set( { layers: layers.concat( layer ) } ); setSelectedId( layer.id ); };
			const removeLayer = function() { if ( ! selected ) return; const next = layers.filter( function( layer ) { return layer.id !== selected.id; } ); set( { layers: next } ); setSelectedId( next[ 0 ] ? next[ 0 ].id : '' ); };
			const duplicateLayer = function() { if ( ! selected ) return; const copy = Object.assign( {}, selected, { id: layerId(), x: clamp( selected.x + 3, 0, 100, 50 ), y: clamp( selected.y + 3, 0, 100, 50 ) } ); set( { layers: layers.concat( copy ) } ); setSelectedId( copy.id ); };
			const chooseBackground = function( media ) { if ( media && media.url ) set( { imageId: media.id || 0, imageUrl: media.url, imageAlt: media.alt || '' } ); };
			const chooseMobileBackground = function( media ) { if ( media && media.url ) set( { mobileImageId: media.id || 0, mobileImageUrl: media.url, mobileImageAlt: media.alt || '' } ); };
			const replaceImage = function( media ) { if ( media && media.url && selected ) updateLayer( selected.id, { imageId: media.id || 0, imageUrl: media.url, imageAlt: media.alt || '' } ); };
			const replaceMobileImage = function( media ) { if ( media && media.url && selected ) updateLayer( selected.id, { mobileImageId: media.id || 0, mobileImageUrl: media.url, mobileImageAlt: media.alt || '' } ); };
			const pointerPosition = function( event ) { const rect = event.currentTarget.closest( '.cni-image-text-layer__stage' ).getBoundingClientRect(); return { x: clamp( ( event.clientX - rect.left ) / rect.width * 100, 0, 100, 50 ), y: clamp( ( event.clientY - rect.top ) / rect.height * 100, 0, 100, 50 ) }; };
			const startDrag = function( event, layer ) { if ( event.button !== 0 ) return; event.preventDefault(); event.stopPropagation(); const point = pointerPosition( event ); dragRef.current = { id: layer.id, offsetX: responsiveNumber( layer, 'x', mobile, 50 ) - point.x, offsetY: responsiveNumber( layer, 'y', mobile, 50 ) - point.y }; setSelectedId( layer.id ); if ( event.currentTarget.setPointerCapture ) event.currentTarget.setPointerCapture( event.pointerId ); };
			const moveDrag = function( event, layer ) { if ( ! dragRef.current || dragRef.current.id !== layer.id ) return; event.preventDefault(); const point = pointerPosition( event ); const changes = mobile ? { mobileX: clamp( point.x + dragRef.current.offsetX, 0, 100, 50 ), mobileY: clamp( point.y + dragRef.current.offsetY, 0, 100, 50 ) } : { x: clamp( point.x + dragRef.current.offsetX, 0, 100, 50 ), y: clamp( point.y + dragRef.current.offsetY, 0, 100, 50 ) }; updateLayer( layer.id, changes ); };
			const endDrag = function( event ) { dragRef.current = null; if ( event.currentTarget.releasePointerCapture && event.currentTarget.hasPointerCapture && event.currentTarget.hasPointerCapture( event.pointerId ) ) event.currentTarget.releasePointerCapture( event.pointerId ); };
			const field = function( label, key, min, max, fallback, step ) { const mobileKey = 'mobile' + key.charAt( 0 ).toUpperCase() + key.slice( 1 ); return el( RangeControl, { label: mobile ? __( 'モバイル', 'cni-blocks' ) + label : __( 'PC', 'cni-blocks' ) + label, value: responsiveNumber( selected, key, mobile, fallback ), min: min, max: max, step: step || 1, onChange: function( value ) { const changes = {}; changes[ mobile ? mobileKey : key ] = clamp( value, min, max, fallback ); updateLayer( selected.id, changes ); } } ); };
			const blockProps = useBlockProps( { className: 'cni-image-text-layer cni-image-text-layer--editor' } );
			const controls = selected ? el( element.Fragment, null,
				selected.type === 'image' ? el( element.Fragment, null,
					el( 'div', { className: 'cni-image-text-layer__selected-image' }, selected.imageUrl ? el( 'img', { src: selected.imageUrl, alt: '' } ) : null, el( MediaUploadCheck, null, el( MediaUpload, { onSelect: replaceImage, allowedTypes: [ 'image' ], value: selected.imageId || 0, render: function( mediaProps ) { return el( Button, { variant: 'secondary', onClick: mediaProps.open }, __( 'PC画像を変更', 'cni-blocks' ) ); } } ) ) ),
					el( MediaUploadCheck, null, el( MediaUpload, { onSelect: replaceMobileImage, allowedTypes: [ 'image' ], value: selected.mobileImageId || 0, render: function( mediaProps ) { return el( Button, { variant: 'secondary', onClick: mediaProps.open }, selected.mobileImageUrl ? __( 'スマホ画像を変更', 'cni-blocks' ) : __( 'スマホ画像を選択（任意）', 'cni-blocks' ) ); } } ) ),
					el( TextControl, { label: __( '画像alt', 'cni-blocks' ), value: selected.imageAlt || '', onChange: function( value ) { updateLayer( selected.id, { imageAlt: value } ); } } ),
					el( TextControl, { label: __( 'リンクURL（任意）', 'cni-blocks' ), type: 'url', value: selected.linkUrl || '', onChange: function( value ) { updateLayer( selected.id, { linkUrl: value } ); } } ),
					el( TextControl, { label: __( 'aria-label（任意）', 'cni-blocks' ), value: selected.ariaLabel || '', onChange: function( value ) { updateLayer( selected.id, { ariaLabel: value } ); } } ),
					el( ToggleControl, { label: __( '新しいタブで開く', 'cni-blocks' ), checked: !! selected.newTab, onChange: function( value ) { updateLayer( selected.id, { newTab: !! value } ); } } )
				) : el( element.Fragment, null,
					el( TextareaControl, { label: __( 'テキスト', 'cni-blocks' ), value: selected.content || '', onChange: function( value ) { updateLayer( selected.id, { content: value } ); } } ),
					el( SelectControl, { label: __( '種類', 'cni-blocks' ), value: selected.role || 'heading', options: [ { label: __( '見出し', 'cni-blocks' ), value: 'heading' }, { label: __( '本文', 'cni-blocks' ), value: 'body' } ], onChange: function( value ) { updateLayer( selected.id, { role: value, fontWeight: value === 'body' ? '400' : '700' } ); } } ),
					el( SelectControl, { label: __( '書体', 'cni-blocks' ), value: selected.fontFamily || 'gothic', options: [ { label: __( 'ゴシック', 'cni-blocks' ), value: 'gothic' }, { label: __( '明朝', 'cni-blocks' ), value: 'mincho' } ], onChange: function( value ) { updateLayer( selected.id, { fontFamily: value } ); } } ),
					el( SelectControl, { label: __( '太さ', 'cni-blocks' ), value: selected.fontWeight || '700', options: [ { label: __( '通常', 'cni-blocks' ), value: '400' }, { label: __( '太字', 'cni-blocks' ), value: '700' } ], onChange: function( value ) { updateLayer( selected.id, { fontWeight: value } ); } } ),
					el( SelectControl, { label: __( '揃え', 'cni-blocks' ), value: selected.textAlign || 'center', options: [ { label: __( '左揃え', 'cni-blocks' ), value: 'left' }, { label: __( '中央揃え', 'cni-blocks' ), value: 'center' }, { label: __( '右揃え', 'cni-blocks' ), value: 'right' } ], onChange: function( value ) { updateLayer( selected.id, { textAlign: value } ); } } ),
					el( 'p', null, __( '文字色', 'cni-blocks' ) ), el( ColorPalette, { value: selected.color || '#1f2937', clearable: false, onChange: function( value ) { updateLayer( selected.id, { color: value || '#1f2937' } ); } } ),
					el( RangeControl, { label: __( '行間', 'cni-blocks' ), value: typeof selected.lineHeight === 'number' ? selected.lineHeight : 1.4, min: .8, max: 3, step: .1, onChange: function( value ) { updateLayer( selected.id, { lineHeight: clamp( value, .8, 3, 1.4 ) } ); } } )
				),
				el( TextControl, { label: __( '追加CSSクラス', 'cni-blocks' ), help: __( '複数指定は半角スペースで区切ります。', 'cni-blocks' ), value: selected.customClass || '', onChange: function( value ) { updateLayer( selected.id, { customClass: value } ); } } ),
				field( __( '横位置（%）', 'cni-blocks' ), 'x', 0, 100, 50 ), field( __( '縦位置（%）', 'cni-blocks' ), 'y', 0, 100, 50 ), field( __( '幅（%）', 'cni-blocks' ), 'width', 5, 100, selected.type === 'image' ? 24 : 30 ), selected.type === 'text' ? field( __( '文字サイズ（px）', 'cni-blocks' ), 'fontSize', 8, 160, 22, .5 ) : null,
				el( Button, { variant: 'secondary', onClick: duplicateLayer }, __( 'このレイヤーを複製', 'cni-blocks' ) ), el( Button, { variant: 'tertiary', isDestructive: true, onClick: removeLayer }, __( 'このレイヤーを削除', 'cni-blocks' ) )
			) : el( 'p', null, __( 'テキストまたは画像を追加してください。', 'cni-blocks' ) );
			return el( element.Fragment, null,
				el( InspectorControls, null,
					el( PanelBody, { title: __( '背景画像', 'cni-blocks' ), initialOpen: true }, el( MediaUploadCheck, null, el( MediaUpload, { onSelect: chooseBackground, allowedTypes: [ 'image' ], value: a.imageId || 0, render: function( mediaProps ) { return el( Button, { variant: 'secondary', onClick: mediaProps.open }, a.imageUrl ? __( 'PC画像を変更', 'cni-blocks' ) : __( 'PC画像を選択', 'cni-blocks' ) ); } } ) ), el( MediaUploadCheck, null, el( MediaUpload, { onSelect: chooseMobileBackground, allowedTypes: [ 'image' ], value: a.mobileImageId || 0, render: function( mediaProps ) { return el( Button, { variant: 'secondary', onClick: mediaProps.open }, a.mobileImageUrl ? __( 'スマホ画像を変更', 'cni-blocks' ) : __( 'スマホ画像を選択（任意）', 'cni-blocks' ) ); } } ) ) ),
					el( PanelBody, { title: __( 'レイヤー', 'cni-blocks' ), initialOpen: true }, el( ButtonGroup, null, el( Button, { variant: device === 'desktop' ? 'primary' : 'secondary', onClick: function() { setDevice( 'desktop' ); } }, __( 'PC編集', 'cni-blocks' ) ), el( Button, { variant: device === 'mobile' ? 'primary' : 'secondary', onClick: function() { setDevice( 'mobile' ); } }, __( 'モバイル編集', 'cni-blocks' ) ) ), el( Button, { variant: 'primary', onClick: addText }, __( 'テキストを追加', 'cni-blocks' ) ), el( MediaUploadCheck, null, el( MediaUpload, { onSelect: addImage, allowedTypes: [ 'image' ], render: function( mediaProps ) { return el( Button, { variant: 'primary', onClick: mediaProps.open }, __( '画像を追加', 'cni-blocks' ) ); } } ) ), layers.length ? el( 'div', { className: 'cni-image-text-layer__layer-list' }, layers.map( function( layer, index ) { return el( Button, { key: layer.id, variant: layer.id === selectedId ? 'primary' : 'secondary', onClick: function() { setSelectedId( layer.id ); } }, ( index + 1 ) + '. ' + layerLabel( layer, index ) ); } ) ) : null, controls )
				),
				el( 'div', blockProps, a.imageUrl ? el( 'div', { className: 'cni-image-text-layer__stage' }, el( 'img', { className: 'cni-image-text-layer__background', src: mobile && a.mobileImageUrl ? a.mobileImageUrl : a.imageUrl, alt: mobile && a.mobileImageUrl ? ( a.mobileImageAlt || a.imageAlt || '' ) : ( a.imageAlt || '' ) } ), layers.map( function( layer, index ) { const x = responsiveNumber( layer, 'x', mobile, 50 ); const y = responsiveNumber( layer, 'y', mobile, 50 ); const width = responsiveNumber( layer, 'width', mobile, layer.type === 'image' ? 24 : 30 ); const size = responsiveNumber( layer, 'fontSize', mobile, 22 ); const current = layer.id === selectedId; const image = layer.type === 'image'; return el( 'div', { key: layer.id, className: 'cni-image-text-layer__item ' + ( image ? 'cni-image-text-layer__item--image' : 'cni-image-text-layer__item--' + ( layer.fontFamily === 'mincho' ? 'mincho' : 'gothic' ) ) + ( current ? ' is-selected' : '' ), style: { left: x + '%', top: y + '%', width: width + '%', fontSize: size + 'px', color: layer.color || '#1f2937', fontWeight: layer.fontWeight || ( layer.role === 'body' ? '400' : '700' ), textAlign: layer.textAlign || 'center', '--cni-itl-line-height': layer.lineHeight || 1.4 }, onClick: function( event ) { event.stopPropagation(); setSelectedId( layer.id ); } }, image ? el( 'img', { className: 'cni-image-text-layer__editor-image', src: mobile && layer.mobileImageUrl ? layer.mobileImageUrl : layer.imageUrl, alt: '' } ) : el( 'div', { className: 'cni-image-text-layer__content', contentEditable: true, suppressContentEditableWarning: true, onClick: function( event ) { event.stopPropagation(); setSelectedId( layer.id ); }, onInput: function( event ) { updateLayer( layer.id, { content: event.currentTarget.textContent || '' } ); } }, layer.content || '' ), current ? el( element.Fragment, null, el( 'button', { type: 'button', className: 'cni-image-text-layer__move-handle', contentEditable: false, 'aria-label': __( 'レイヤーを移動', 'cni-blocks' ), onPointerDown: function( event ) { startDrag( event, layer ); }, onPointerMove: function( event ) { moveDrag( event, layer ); }, onPointerUp: endDrag, onPointerCancel: endDrag }, '✋' ), el( 'span', { className: 'cni-image-text-layer__selected-label', contentEditable: false }, ( index + 1 ) + '. ' + __( '編集中', 'cni-blocks' ) ) ) : null ); } ) ) : el( MediaUploadCheck, null, el( MediaUpload, { onSelect: chooseBackground, allowedTypes: [ 'image' ], value: a.imageId || 0, render: function( mediaProps ) { return el( Button, { variant: 'primary', onClick: mediaProps.open }, __( '背景画像を選択', 'cni-blocks' ) ); } } ) ) )
			);
		}, save: function() { return null; }
	} );
} )( window.wp.blocks, window.wp.element, window.wp.blockEditor, window.wp.components, window.wp.i18n );
